name: PR CI

on:
  pull_request:

jobs:

  client-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json
    - run: npm ci
    - run: npm test

  server-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json
    - run: npm ci
    - run: npm test
